# Generated by Django 3.2.3 on 2021-07-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_text',
            new_name='text',
        ),
    ]
