# Generated by Django 3.2.3 on 2021-07-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_rename_comment_text_comments_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_published',
            field=models.BooleanField(default=0),
        ),
    ]
