# Generated by Django 3.2.3 on 2021-08-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_remove_posts_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
